ehr: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/Overall.xlsx'
mri: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/HCM_MRI_Database_03022022.xlsx'
rv_insertion: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/RV_insertion_patients_list.xlsx'
ecg: str = 'Data/ECG/ScarECG'
ecg_ucsf = 'Data/ECG/UCSF'
ecg_loc: str = 'Data/ECG/ScarLocationECG'
ecg_augmented: str = 'Data/ECG/ScarECG/Augmented'
website_ecg: str = 'Data/ECG/WebsiteECG'
muse: str = 'Data/ECG/MUSE'
muse_ucsf: str = '/Users/kasra/Library/CloudStorage/OneDrive-UniversityofDelaware-o365/UCSF Data/UCSF_MUSE'
pla_annotation: str = 'Data/ECG/ScarECG/PLAAnnotation'
pla_annotation_loc: str = 'Data/ECG/ScarLocationECG/PLAAnnotation'
pla_annotation_ucsf: str = 'Data/ECG/UCSF_PLAAnnotation'
pla_annotation_augmented: str = 'Data/ECG/ScarECG/Augmented/PLAAnnotation'
website_pla_annotation: str = 'Data/ECG/WebsiteECG/PLAAnnotation'
fqrs_annotation: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/ECG_Talha_Fragmentation.xlsx'
cached_imputed_ehr: str = 'Data/CachedEHR/ehr_df.xlsx'
cached_scar_ecg_meta: str = 'Data/ECG/ScarECG/scar_ecg_meta.xlsx'
scar_ecg_augmented_meta: str = 'Data/ECG/ScarECG/Augmented/scar_ecg_augmented_meta.xlsx'
website_ecg_meta: str = 'Data/ECG/WebsiteECG/website_ecg_meta.xlsx'
ecg_meta_loc: str = 'Data/ECG/ecg_scar_location.xlsx'
qt_segment_dataset: str = 'Data/Dataset/QTSegment'
cached_qt_segment_dataset: str = 'Data/Dataset/QTSegment/qt_segment_dataset.npy'
scar_location = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/HCM_LGElocalization_Database_03022022.xlsx'
scar_location_augmented = 'Data/ECG/ScarECG/Augmented/scar_location_augmented.xlsx'

sanjay_check = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/sanjay_check.xlsx'
sanjay_check_v2 = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/sanjay_check_v2.xlsx'
ucsf_mri = '/Users/kasra/Library/CloudStorage/OneDrive-UniversityofDelaware-o365/UCSF Data/UCSF_MRI.xlsx'
ucsf_meta = '/Users/kasra/Library/CloudStorage/OneDrive-UniversityofDelaware-o365/UCSF Data/UCSF_Meta.xlsx'

OneYearECGs = 'Data/ECG/HopkinsOneYearECGs'


